"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "../components/provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Factify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <NextAuthProvider>
        <body>{children}</body>
      </NextAuthProvider>
    </html>
  );
}
