import "../globals.css";
import { Inter } from "next/font/google";
import { HeaderTemplate } from "@/components/header/Header";
import { SideBar } from "@/components/sidebar/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Factify",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <HeaderTemplate
          userName="Rodrigo Viveros"
          role="Administrador"
        ></HeaderTemplate>
        <main className="outlet">
          <SideBar />
          <article>{children}</article>
        </main>
      </body>
    </html>
  );
}
