"use client";
import "../globals.css";
import { Inter } from "next/font/google";
import { SideBar } from "@/components/sidebar/side-bar";
import { HeaderTemplate } from "@/components/header/Header";
import { SessionProvider } from "next-auth/react";
import { Footer } from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Factify",
  description: "Generated by create next app",
};
// CRW añadir footer
export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <SessionProvider>
        <SideBar />
        <main className="outlet">
          <HeaderTemplate userName="Rodrigo Viveros" role="Administrador" />
          <article>{children}</article>
        </main>
      </SessionProvider>
    </>
  );
}
